main: sphere reference

sphere: propagation-sphere.c propagation-sphere.h
	gcc propagation-sphere.c -o propagation-sphere
reference: propagation-reference.c propagation-reference.h
	gcc propagation-reference.c -o propagation-reference
clean:
	rm propagation-sphere propagation-reference