include $(OPS_INSTALL_PATH)/../makefiles/Makefile.common
include $(OPS_INSTALL_PATH)/../makefiles/Makefile.mpi
include $(OPS_INSTALL_PATH)/../makefiles/Makefile.cuda

HEADERS=forward-ops.h utils.h

OPS_FILES=forward-ops.cpp

OPS_GENERATED=forward-ops_ops.cpp

APP=forward-ops
MAIN_SRC=forward-ops

include $(OPS_INSTALL_PATH)/../makefiles/Makefile.c_app